import { dependencies } from '../../../../../package.json';

/**
 * Engineering constants for occurrence materialization — deliberately configuration, not product
 * limits. The window bounds how far recurrence is expanded ahead of time; navigation beyond it
 * extends the window rather than hitting a wall.
 */

/** The initial window around „now“: 6 months back for agenda scrolling, 18 months ahead. */
export const WINDOW_PAST_MONTHS = 6;
export const WINDOW_FUTURE_MONTHS = 18;

/**
 * When a range query comes this close to a coverage edge, the window is extended — the user is
 * clearly navigating there.
 */
export const WINDOW_EDGE_THRESHOLD_MONTHS = 1;

/** How far one extension pushes the edge out. */
export const WINDOW_EXTENSION_MONTHS = 6;

/**
 * Hard cap per series inside the window. A sane rule stays far below it (daily over two years is
 * ~730 rows); only a pathological rule reaches it, and such a series is truncated and its source
 * flagged rather than allowed to fill the table.
 */
export const MAX_OCCURRENCES_PER_SERIES = 10_000;

/** Safety cap handed to the recurrence engine so a broken rule cannot iterate forever. */
export const MAX_RULE_ITERATIONS = 100_000;

/**
 * Stamped into every coverage row; a mismatch tells the app the derived rows were generated by an
 * older engine and triggers a full rebuild.
 *
 * Read directly from `package.json` instead of being hand-typed, so it can never drift from what
 * is actually installed — there is nothing to keep in sync. `rrule-temporal` is still pinned to an
 * **exact** version there (no `^`): an engine "version" that were itself a range (`^2.0.2`) would
 * not identify one fixed set of behaviour, which defeats the point of stamping it.
 */
export const RECURRENCE_ENGINE_VERSION = `rrule-temporal@${dependencies['rrule-temporal']}`;
