// Generated by scripts/generate-app-version.mjs from package.json. Do not edit by hand.
/** The app's released version, as shown in Settings and on the "Über die App" screen. */
export const APP_VERSION = '0.0.0';
