import { TestBed } from '@angular/core/testing';

import { CalendarRepository } from '@app/data/calendar/calendar.repository';
import { localDaysOf } from '@app/data/calendar/device-normalizer';
import { RECURRENCE_ENGINE_VERSION } from '@app/data/calendar/recurrence/materialization-config';
import { CalendarSourceDao } from '@app/data/daos/calendar-source.dao';
import { OccurrenceDao } from '@app/data/daos/occurrence.dao';
import { SQLITE_DATABASE } from '@app/data/gateways/sqlite-database';
import { InMemorySqliteDatabase } from '@app/data/gateways/sqlite-database.testing';
import { MIGRATIONS } from '@app/data/migrations/migrations';
import { CalendarMaintenanceInteractor } from './calendar-maintenance.interactor';

const CONTEXT = { nowUtc: '2026-08-06T12:00:00Z', timeZone: 'Europe/Vienna' };

describe('CalendarMaintenanceInteractor', () => {
  let database: InMemorySqliteDatabase;
  let interactor: CalendarMaintenanceInteractor;
  let occurrences: OccurrenceDao;

  beforeEach(async () => {
    localStorage.removeItem('rk.calendar-maintenance');
    database = new InMemorySqliteDatabase();
    database.migrate(MIGRATIONS);

    TestBed.resetTestingModule();
    TestBed.configureTestingModule({
      providers: [{ provide: SQLITE_DATABASE, useValue: database }],
    });

    interactor = TestBed.inject(CalendarMaintenanceInteractor);
    occurrences = TestBed.inject(OccurrenceDao);

    const sources = TestBed.inject(CalendarSourceDao);
    await sources.insertSource({
      id: 'source-1',
      type: 'app',
      name: 'App',
      enabled: true,
      state: 'ok',
      createdAt: '2026-08-01T09:00:00.000Z',
      updatedAt: '2026-08-01T09:00:00.000Z',
    });
    await sources.insertCalendar({
      id: 'calendar-1',
      sourceId: 'source-1',
      name: 'Termine',
      color: null,
      emoji: null,
      enabled: true,
      writable: true,
      externalId: null,
      createdAt: '2026-08-01T09:00:00.000Z',
      updatedAt: '2026-08-01T09:00:00.000Z',
    });
    const repository = TestBed.inject(CalendarRepository);
    await repository.createItem(
      {
        id: 'item-1',
        calendarId: 'calendar-1',
        kind: 'event',
        title: 'Plenum',
        location: null,
        note: null,
        start: { kind: 'utc', value: '2026-09-07T12:00:00Z', timeZone: null },
        end: { kind: 'utc', value: '2026-09-07T13:00:00Z', timeZone: null },
        rrule: null,
        predecessorSeriesId: null,
        ruleRevision: 0,
        createdAt: '2026-08-01T10:00:00.000Z',
        updatedAt: '2026-08-01T10:00:00.000Z',
      },
      CONTEXT,
    );
  });

  afterEach(() => {
    database.close();
    localStorage.removeItem('rk.calendar-maintenance');
  });

  it('rebuilds derived rows generated by an older engine version', async () => {
    const coverage = await occurrences.findCoverage('source-1');
    await occurrences.upsertCoverage({ ...coverage!, engineVersion: 'rrule-temporal@0.0.1' });

    await interactor.ensureConsistency();

    const repaired = await occurrences.findCoverage('source-1');
    expect(repaired!.engineVersion).toBe(RECURRENCE_ENGINE_VERSION);
    await expect(
      occurrences.listInRange('2026-09-01T00:00:00Z', '2026-10-01T00:00:00Z'),
    ).resolves.toHaveLength(1);
  });

  it('does nothing when zone and engine are unchanged', async () => {
    await interactor.ensureConsistency();
    const before = await occurrences.findCoverage('source-1');

    await interactor.ensureConsistency();

    await expect(occurrences.findCoverage('source-1')).resolves.toEqual(before);
  });

  it('rebuilds after a device timezone change', async () => {
    localStorage.setItem(
      'rk.calendar-maintenance',
      JSON.stringify({ lastTimeZone: 'America/New_York' }),
    );
    const before = await occurrences.findCoverage('source-1');

    await interactor.ensureConsistency();

    const after = await occurrences.findCoverage('source-1');
    expect(after!.updatedAt).not.toBe(before!.updatedAt);
  });

  it('recomputes cached device rows into the new zone without a native refresh', async () => {
    const deviceRow = {
      id: 'device:ios:cal-1:event-1#2026-08-10T02:00:00Z',
      sourceId: 'device',
      sourceType: 'device' as const,
      calendarId: 'device-cal:cal-1',
      seriesId: null,
      originalStart: null,
      provenance: 'device-cached' as const,
      itemKind: 'event' as const,
      title: 'Zahnarzt',
      location: null,
      isAllDay: false,
      start: { kind: 'utc' as const, value: '2026-08-10T02:00:00Z', timeZone: null },
      end: { kind: 'utc' as const, value: '2026-08-10T03:00:00Z', timeZone: null },
      startUtc: '2026-08-10T02:00:00Z',
      endUtc: '2026-08-10T03:00:00Z',
      // Deliberately wrong for every real zone, so any correct recompute changes it.
      startLocalDay: '1970-01-01',
      endLocalDay: '1970-01-01',
      externalId: 'event-1',
    };
    await occurrences.insertMany([deviceRow]);
    localStorage.setItem(
      'rk.calendar-maintenance',
      JSON.stringify({ lastTimeZone: 'America/New_York' }),
    );

    await interactor.ensureConsistency();

    const currentZone = Intl.DateTimeFormat().resolvedOptions().timeZone;
    const expected = localDaysOf(deviceRow.startUtc, deviceRow.endUtc, currentZone);
    const [repaired] = await occurrences.listInRange(
      '2026-08-01T00:00:00Z',
      '2026-08-31T00:00:00Z',
    );
    expect(repaired.startLocalDay).toBe(expected.startLocalDay);
    expect(repaired.endLocalDay).toBe(expected.endLocalDay);
  });

  it('does not touch device rows when only the recurrence engine changed', async () => {
    const deviceRow = {
      id: 'device:ios:cal-1:event-1#2026-08-10T02:00:00Z',
      sourceId: 'device',
      sourceType: 'device' as const,
      calendarId: 'device-cal:cal-1',
      seriesId: null,
      originalStart: null,
      provenance: 'device-cached' as const,
      itemKind: 'event' as const,
      title: 'Zahnarzt',
      location: null,
      isAllDay: false,
      start: { kind: 'utc' as const, value: '2026-08-10T02:00:00Z', timeZone: null },
      end: { kind: 'utc' as const, value: '2026-08-10T03:00:00Z', timeZone: null },
      startUtc: '2026-08-10T02:00:00Z',
      endUtc: '2026-08-10T03:00:00Z',
      startLocalDay: '1970-01-01',
      endLocalDay: '1970-01-01',
      externalId: 'event-1',
    };
    await occurrences.insertMany([deviceRow]);
    const coverage = await occurrences.findCoverage('source-1');
    await occurrences.upsertCoverage({ ...coverage!, engineVersion: 'rrule-temporal@0.0.1' });

    await interactor.ensureConsistency();

    const [row] = await occurrences.listInRange('2026-08-01T00:00:00Z', '2026-08-31T00:00:00Z');
    expect(row.startLocalDay).toBe('1970-01-01');
  });
});
